### ISSUE TITLE
the behavior of model generation when only one label is defined confuses me a bit

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/edge-ml#17]
can you please explain, it appears that if only one label is defined, still two classes are predicted?

**Comment by KtrauM** [comment]
Not labeled parts are regarded as labeled with "Other".

**Comment by KtrauM** [comment]
[Added an option to define the behaviour](https://github.com/edge-ml/ml/commit/97be2227a8bbded1ea38fe8a46e08acc42b90cba)
User may be able to choose if they want to include or omit (default) the datapoints which are not labelled. I can merge it to master, if you like the new behaviour.
