### ISSUE TITLE
Cannot connect Nicla Sense

### ISSUE THREAD

**Issue by ralphjy** [edge-ml/edge-ml#22]
I'm trying to connect a Nicla Sense to collect data but even though it is found and pairs successfully - the device does not show as connected, so I can't collect any data.

I've had this problem with the standalone bhy-controller where it would connect but would not show that it was connected.  I could still get sensor data.  This was using an executable that I built from the current github repo.  I downloaded the pre-built bhy_1.0.3 executable and it would show the connect correctly.  Is it possible that you are having the same problem.

**Comment by TobiasRoeddiger** [comment]
Did you follow the instructions [here](https://github.com/edge-ml/EdgeML-Arduino) to flash the latest edge-ml firmware on your Nicla?

**Comment by ralphjy** [comment]
Yes, I did all that last night and flashed it this morning.  I am using Arduino IDE 1.8.13.

I can see that the device does pair.

I will try this with the Nano33BLESense.  I've never tried it with WebBLE.   As I mentioned my Nicla does work correctly when I use bhy_1.0.3.  I am on Windows10 using Chrome.

**Comment by TobiasRoeddiger** [comment]
Thanks, yes WebBLE is shaky from time to time. Does the Chrome Developer Console print any errors?

**Comment by ralphjy** [comment]
The Nano had the same issue - pairs but doesn't indicate connected.

I do see an error in the console.  Maybe I missed a step somewhere?

![image](https://user-images.githubusercontent.com/31114486/162631668-394d9155-2acc-4654-bb8c-a977903153a3.png)

**Comment by TobiasRoeddiger** [comment]
@tk-king any ideas?

**Comment by TobiasRoeddiger** [comment]
@ralphjy can you check which version of the edge-ml library you have installed in your Arduino IDE?

**Comment by ralphjy** [comment]
1.1.2

I tried downgrading to 1.1.0 but had the same result (had to rename the EdgeML.h file in the App when downgrading)

**Comment by tk-king** [comment]
This seems to be a server issue.

I am working on it.

**Comment by tk-king** [comment]
The problem should be fixed now. An old image of the backend server was deployed on the server.
