### ISSUE TITLE
BSEC Data for Nicla Sense

### ISSUE THREAD

**Issue by ralphjy** [edge-ml/edge-ml#23]
This is more a feature request than an issue.

Could you also provide the BSEC data - sIAQ, bVOCeq, CO2eq

Thanks,

Ralph

**Comment by TobiasRoeddiger** [comment]
Thanks for the suggestion. Currently we are focused on finalizing the machine learning part of the edge-ml. We are happy to receive contributions or consider this in a future sprint! :)
