### ISSUE TITLE
 Kontextsensitive Systeme Lecture

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/edge-ml#24]
For the lecture we have to verify/expand some of the existing features:
| Deadline  | Functionality | Finished |
| ------------- | ------------- | ------------- |
 | May 3rd  | data can be pushed using JS library (need example code). It should be possible to assign an ID that relates to the user that the data was collected with for LOSO valdiation. Also, it would be good if alabel can be set for a complete dataset from the JS library.  | No
| May 10th | It should be possible to download datasets including labels. Also, it should include the unique identifier pertaining to the id of the person that the dataset belongs to (probably not the user id).  | No |

Additional requirements will be added later.

**Comment by tk-king** [comment]
Currently it is possible to download data sets with the labels through our csv-format. 
How would we deal with the metadata (e.g. the unique identifier) ?  
Should we provide an extra file for each dataset with the metadata? 
We could also include the metadata in our csv format with the '#' character. The disadvantage is that not every library supports these comments in the csv file.

**Comment by TobiasRoeddiger** [comment]
metadata should be a json atring, in the csv we can add it as comment as you suggested

**Comment by TobiasRoeddiger** [comment]
Btw, we have the python library anyways - metadata shouldn‘t be a problem here.
