### ISSUE TITLE
expired certificate for beta.edge-ml.org

### ISSUE THREAD

**Issue by riedel** [edge-ml/edge-ml#32]
Let's encrypt expired Sat, 16 Jul 2022 08:17:42 GMT, so it seems that the autorenewal fails

**Comment by omeryagmurlu** [comment]
I've renewed the certificate manually for now, will take a look at autorenewal

**Comment by riedel** [comment]
Just FYI: you actually did not get a cerficate for beta.edge-ml.org but for beta.edge-ml-beta.dmz.teco.edu
