### ISSUE TITLE
support leave one out validation

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/edge-ml#36]
We should add leave one out validation. The way I imagine it would work is as follows:
- users add whatever metadata fields (e.g., userId: 123)
- when configuring the training of a model, one field can be selected as "leave one out" variable so for example if userId is selected, all datasets with unique values for userId are grouped as one and challenged against the others

**Comment by riedel** [comment]
To make it extensible I think one should be able to select a metadata key for LOSO.

**Comment by TobiasRoeddiger** [comment]
> To make it extensible I think one should be able to select a metadata key for LOSO.

yes, definetly!
