### ISSUE TITLE
update website

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/edge-ml#5]
code example should be correct
all links should work and point at the correct git (some still pointing at the old github explorer)

**Comment by TobiasRoeddiger** [comment]
links are working now.

**Comment by tk-king** [comment]
Code is updated now

**Comment by TobiasRoeddiger** [comment]
- move to loop function
- add favicon (bright and dark mode)

**Comment by tk-king** [comment]
Updated code example and favicon
