### ISSUE TITLE
set up automatic production deployment

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/edge-ml#8]
currently we have to pull the latest version manually

we should set up CD for the future

**Comment by tk-king** [comment]
Maybe we could use something like that Watchtower (https://containrrr.dev/watchtower/) to autoamtically pull the images from Docker Hub.

**Comment by TobiasRoeddiger** [comment]
i think it is good if we keep the manual pulling of the release. for beta we now have the automatic pulling so i will close this ticket
